name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'src'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/Ontology.sln

    - name: Build
      run: dotnet build src/Ontology.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/Ontology.Tests/Ontology.Tests.csproj --no-restore --configuration Release --collect:"XPlat Code Coverage"
